# Servidor
server.port=8081
spring.application.name=ms-datos-organizacionales

# MongoDB Atlas — la URI completa ya incluye la base de datos
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/cordillera_datos}

# Logs
logging.level.cl.cordillera=DEBUG
